import { spawnSync } from "node:child_process";
import { readFileSync } from "node:fs";
import { resolve } from "node:path";
import { createHash } from "node:crypto";

const root = process.cwd();
const outputPath = resolve(root, "THIRD-PARTY-NOTICES.md");

interface PkgEntry {
  name: string;
  versions: string[];
  license: string;
  homepage?: string;
  description?: string;
  author?: string;
}

function runPnpmLicenses(): string {
  const result = spawnSync("pnpm", ["licenses", "list", "--json", "--silent"], {
    cwd: root, env: { ...process.env, NODE_OPTIONS: "--no-deprecation" },
    encoding: "utf8",
    shell: true
  });
  if (result.status !== 0) {
    console.error("pnpm licenses list failed:", result.stderr || result.stdout);
    process.exit(result.status ?? 1);
  }
  return result.stdout;
}

function parseEntries(stdout: string): PkgEntry[] {
  const report = JSON.parse(stdout) as Record<string, Array<{
    name: string;
    versions: string[];
    license: string;
    homepage?: string;
    description?: string;
    author?: string;
  }>>;
  const entries: PkgEntry[] = [];
  const directNames = directDependencyNames();
  for (const [license, items] of Object.entries(report)) {
    for (const item of items) {
      if (!directNames.has(item.name)) continue;
      entries.push({
        name: item.name,
        versions: item.versions,
        license,
        homepage: item.homepage,
        description: item.description,
        author: item.author
      });
    }
  }
  entries.sort((a, b) => {
    const nameCmp = a.name.localeCompare(b.name);
    return nameCmp !== 0 ? nameCmp : a.license.localeCompare(b.license);
  });
  return entries;
}

function expectedOutput(stdout: string): string {
  const entries = parseEntries(stdout);
  const lockfileText = readFileSync(resolve(root, "pnpm-lock.yaml"), "utf8");
  const lockfileMatch = lockfileText.match(/^lockfileVersion:\s*['\"]?([0-9.]+)/m);
  const lockfileVersion = lockfileMatch ? lockfileMatch[1] : "unknown";
  const generatedAt = new Date().toISOString();
  const lines: string[] = [];
  lines.push("# Third-party notices");
  lines.push("");
  lines.push("Auto-generated by `pnpm run licenses:generate` on " + generatedAt + ".");
  lines.push("");
  lines.push("This file lists direct runtime and development dependencies declared by each workspace,");
  lines.push("together with the license declared by each package. It is regenerated whenever");
  lines.push("the lockfile changes. Do not edit by hand; CI runs `pnpm run licenses:check` to");
  lines.push("fail the build if this file drifts.");
  lines.push("");
  lines.push("- pnpm lockfile version: `" + lockfileVersion + "`");
  lines.push("- Total entries: " + entries.length);
  lines.push("");
  lines.push("## License summary");
  lines.push("");
  const licenseCounts = new Map<string, number>();
  for (const entry of entries) {
    licenseCounts.set(entry.license, (licenseCounts.get(entry.license) ?? 0) + 1);
  }
  const sortedLicenses = Array.from(licenseCounts.entries()).sort((a, b) => a[0].localeCompare(b[0]));
  for (const [license, count] of sortedLicenses) lines.push("- `" + license + "`: " + count);
  lines.push("");
  lines.push("## Packages");
  lines.push("");
  for (const entry of entries) {
    lines.push("### " + entry.name + "@" + entry.versions.join(", "));
    lines.push("");
    lines.push("- License: `" + entry.license + "`");
    if (entry.author) lines.push("- Author: " + entry.author);
    if (entry.homepage) lines.push("- Homepage: " + entry.homepage);
    if (entry.description) lines.push("- Description: " + entry.description);
    lines.push("");
  }
  return lines.join("\n");
}

// Strip volatile header (timestamp + total entries count + lockfile version) so the
// structural comparison is stable across generations but still catches license drift
// (added/removed/changed packages).
function structural(input: string): string {
  return input
    .replace(/Auto-generated by `pnpm run licenses:generate` on .*\./, "TIMESTAMP")
    .replace(/- Total entries: .*/, "- Total entries: N")
    .replace(/- pnpm lockfile version: .*/, "- pnpm lockfile version: V");
}

const stdout = runPnpmLicenses();
const current = readFileSync(outputPath, "utf8");
const expected = expectedOutput(stdout);

const currentHash = createHash("sha256").update(structural(current)).digest("hex");
const expectedHash = createHash("sha256").update(structural(expected)).digest("hex");

if (currentHash !== expectedHash) {
  console.error("THIRD-PARTY-NOTICES.md is out of date with the current lockfile.");
  console.error("Run `pnpm run licenses:generate` and commit the result.");
  process.exit(1);
}

console.log("THIRD-PARTY-NOTICES.md matches the lockfile (sha256=" + currentHash.slice(0, 12) + ").");

function directDependencyNames(): Set<string> {
  const names = new Set<string>();
  for (const relativePath of ["package.json", "apps/admin/package.json"]) {
    const packageJson = JSON.parse(readFileSync(resolve(root, relativePath), "utf8")) as {
      dependencies?: Record<string, string>;
      devDependencies?: Record<string, string>;
      optionalDependencies?: Record<string, string>;
    };
    for (const field of ["dependencies", "devDependencies", "optionalDependencies"] as const) {
      for (const name of Object.keys(packageJson[field] ?? {})) names.add(name);
    }
  }
  return names;
}
