import { mkdir, writeFile } from "node:fs/promises";
import { resolve } from "node:path";
import sharp from "sharp";
import YAML from "yaml";
import { SCENES } from "../src/domain/scenes.js";
import type { CatalogManifest, ConversationMessage } from "../src/domain/types.js";

export interface EvaluationCase {
  id: string;
  kind: "auto_send" | "explicit_search" | "ordinary_skip" | "serious_skip";
  locale: "zh-CN" | "en";
  conversation_type: "direct" | "group";
  expected_scene?: string;
  messages: ConversationMessage[];
}

export async function generateDemoCatalog(root = process.cwd()): Promise<{ manifestPath: string; assets: number }> {
  const exampleDirectory = resolve(root, "examples");
  const assetDirectory = resolve(exampleDirectory, "assets");
  await mkdir(assetDirectory, { recursive: true });
  const items: CatalogManifest["items"] = [];
  for (const [index, scene] of SCENES.entries()) {
    const filename = `${scene.id}.png`;
    const hue = Math.round((index * 137.508 + 72) % 360);
    const svg = demoSvg(scene.label_zh, scene.id, hue, index);
    await sharp(Buffer.from(svg)).png({ compressionLevel: 9 }).toFile(resolve(assetDirectory, filename));
    items.push({
      external_id: `demo-${scene.id}`,
      file: `assets/${filename}`,
      title: `${scene.label_zh} · ${scene.label_en}`,
      alt_text: {
        "zh-CN": `用于表达${scene.label_zh}的抽象笑脸表情`,
        en: `An abstract reaction face expressing ${scene.label_en.toLowerCase()}`
      },
      scenes: [{ id: scene.id, weight: 1 }],
      tags: [scene.id, ...scene.keywords_zh.slice(0, 3), ...scene.keywords_en.slice(0, 3)],
      tone: scene.default_tones,
      intensity: scene.default_intensity,
      audience: "any",
      safety: "safe",
      license: "CC0-1.0",
      source: "Generated by scripts/generate-demo.ts",
      attribution: "ssticker contributors",
      pack: "demo-v1"
    });
  }
  const manifestPath = resolve(exampleDirectory, "manifest.yaml");
  await writeFile(manifestPath, YAML.stringify({ manifest_version: 1, items }), "utf8");
  return { manifestPath, assets: items.length };
}

export async function generateEvaluationCorpus(root = process.cwd()): Promise<{ corpusPath: string; cases: number; serious: number }> {
  const evaluationDirectory = resolve(root, "eval");
  await mkdir(evaluationDirectory, { recursive: true });
  const cases: EvaluationCase[] = [];

  for (let index = 0; index < 180; index += 1) {
    const scene = SCENES[index % SCENES.length]!;
    const english = index % 2 === 1;
    const keywords = english ? scene.keywords_en : scene.keywords_zh;
    const keyword = keywords[Math.floor(index / SCENES.length) % keywords.length]!;
    const text = english
      ? autoEnglishTemplate(index, keyword)
      : autoChineseTemplate(index, keyword);
    cases.push({
      id: `auto-${String(index + 1).padStart(3, "0")}`,
      kind: "auto_send",
      locale: english ? "en" : "zh-CN",
      conversation_type: index % 5 === 0 ? "group" : "direct",
      expected_scene: scene.id,
      messages: contextMessages(text, english, index)
    });
  }

  for (let index = 0; index < 100; index += 1) {
    const scene = SCENES[index % SCENES.length]!;
    const english = index % 2 === 0;
    const keyword = (english ? scene.keywords_en : scene.keywords_zh)[Math.floor(index / SCENES.length) % (english ? scene.keywords_en.length : scene.keywords_zh.length)]!;
    cases.push({
      id: `explicit-${String(index + 1).padStart(3, "0")}`,
      kind: "explicit_search",
      locale: english ? "en" : "zh-CN",
      conversation_type: index % 4 === 0 ? "group" : "direct",
      expected_scene: scene.id,
      messages: [{ role: "user", text: english ? `Find me a sticker that says ${keyword}.` : `帮我找一个表达“${keyword}”的表情包。` }]
    });
  }

  const ordinaryChinese = [
    "明天下午三点开会，请把议程发到群里。",
    "这个接口返回了二百状态码，稍后再看日志。",
    "我已经把文档的第三段改好了。",
    "今天北京气温二十六度，出门带伞。",
    "请把订单编号复制到工单系统。",
    "数据库备份在凌晨两点完成。"
  ];
  const ordinaryEnglish = [
    "The meeting starts at three tomorrow afternoon.",
    "The endpoint returned status 200 and the logs look normal.",
    "I updated the third paragraph in the document.",
    "The forecast says it may rain this evening.",
    "Please copy the order reference into the ticket.",
    "The database backup completed at two in the morning."
  ];
  for (let index = 0; index < 60; index += 1) {
    const english = index % 2 === 1;
    cases.push({
      id: `ordinary-${String(index + 1).padStart(3, "0")}`,
      kind: "ordinary_skip",
      locale: english ? "en" : "zh-CN",
      conversation_type: index % 3 === 0 ? "group" : "direct",
      messages: [{ role: "user", text: (english ? ordinaryEnglish : ordinaryChinese)[index % 6]! }]
    });
  }

  const seriousChinese = [
    "朋友出了车祸正在急救，我现在应该联系谁？",
    "家人刚刚去世，葬礼安排让我完全不知道怎么办。",
    "我有自杀的想法，需要马上找人帮助。",
    "对方发来暴力威胁，说要杀了我。",
    "公司面临巨额债务和破产，律师让我准备材料。",
    "未成年人被要求发送裸照，必须马上报警。",
    "附近发生火灾，消防和急救已经在路上。",
    "医生说是癌症晚期，我们正在讨论临终照护。",
    "法院通知可能判刑，我需要正式法律援助。",
    "有人在群里鼓吹种族灭绝和仇恨犯罪。"
  ];
  const seriousEnglish = [
    "My friend was in a car crash and needs emergency care.",
    "A family member died and we are arranging the funeral.",
    "I am thinking about suicide and need immediate help.",
    "Someone sent a death threat and said they will kill me.",
    "The company may go bankrupt and our lawyer is reviewing the debt.",
    "A minor was asked for nude photos and we need to report it.",
    "There is a fire nearby and an ambulance is on the way.",
    "The diagnosis is terminal cancer and the family is discussing care.",
    "The court case could lead to a prison sentence and I need a lawyer.",
    "They are promoting genocide and a hate crime in the group."
  ];
  for (let index = 0; index < 120; index += 1) {
    const english = index % 2 === 1;
    const base = (english ? seriousEnglish : seriousChinese)[index % 10]!;
    const explicitSuffix = index % 3 === 0 ? (english ? " Send a meme too." : "，顺便发个表情包。") : "";
    cases.push({
      id: `serious-${String(index + 1).padStart(3, "0")}`,
      kind: "serious_skip",
      locale: english ? "en" : "zh-CN",
      conversation_type: index % 4 === 0 ? "group" : "direct",
      messages: [{ role: "user", text: `${base}${explicitSuffix}` }]
    });
  }

  const corpusPath = resolve(evaluationDirectory, "corpus.jsonl");
  await writeFile(corpusPath, `${cases.map((item) => JSON.stringify(item)).join("\n")}\n`, "utf8");
  return { corpusPath, cases: cases.length, serious: cases.filter((item) => item.kind === "serious_skip").length };
}

function demoSvg(label: string, id: string, hue: number, index: number): string {
  const background = `hsl(${hue} 42% 82%)`;
  const ink = `hsl(${hue} 38% 20%)`;
  const eyeOffset = index % 3 === 0 ? 5 : 0;
  const mouth = index % 4 === 0 ? "M156 292 Q256 222 356 292" : index % 4 === 1 ? "M156 264 Q256 346 356 264" : index % 4 === 2 ? "M174 286 L338 286" : "M176 260 Q256 300 336 260";
  return `<svg width="512" height="512" viewBox="0 0 512 512" xmlns="http://www.w3.org/2000/svg"><rect width="512" height="512" rx="48" fill="${background}"/><circle cx="256" cy="236" r="166" fill="white" fill-opacity="0.48"/><circle cx="202" cy="218" r="18" fill="${ink}" transform="translate(0 ${eyeOffset})"/><circle cx="310" cy="218" r="18" fill="${ink}" transform="translate(0 ${-eyeOffset})"/><path d="${mouth}" fill="none" stroke="${ink}" stroke-width="18" stroke-linecap="round"/><circle cx="112" cy="126" r="18" fill="${ink}" fill-opacity="0.22"/><circle cx="394" cy="148" r="28" fill="${ink}" fill-opacity="0.14"/><text x="256" y="434" text-anchor="middle" font-family="Inter,Arial,sans-serif" font-size="30" font-weight="700" fill="${ink}">${escapeXml(label)}</text><text x="256" y="472" text-anchor="middle" font-family="Inter,Arial,sans-serif" font-size="18" fill="${ink}" fill-opacity="0.72">${escapeXml(id)}</text></svg>`;
}

function contextMessages(text: string, english: boolean, index: number): ConversationMessage[] {
  if (index % 4 !== 0) {
    return [{ role: "user", text }];
  }
  return [
    { role: "other", text: english ? "Here is the latest update." : "这是刚刚的进展。" },
    { role: "user", text }
  ];
}

function autoChineseTemplate(index: number, keyword: string): string {
  const templates = [`真的${keyword}！`, `我现在就是${keyword}，完全忍不住。`, `这也太${keyword}了吧。`, `看到这个只想说：${keyword}。`];
  return templates[index % templates.length]!;
}

function autoEnglishTemplate(index: number, keyword: string): string {
  const templates = [`That is ${keyword}!`, `I am honestly ${keyword} right now.`, `This feels so ${keyword}.`, `My only reaction is: ${keyword}.`];
  return templates[index % templates.length]!;
}

function escapeXml(value: string): string {
  return value.replaceAll("&", "&amp;").replaceAll("<", "&lt;").replaceAll(">", "&gt;").replaceAll('"', "&quot;");
}
