import { spawnSync } from "node:child_process";
process.noDeprecation = true;
import { readFileSync, writeFileSync } from "node:fs";
import { resolve } from "node:path";

interface PnpmLicenseEntry {
  name: string;
  versions: string[];
  license: string;
  homepage?: string;
  description?: string;
  author?: string;
  paths?: string[];
}

type PnpmLicenseReport = Record<string, PnpmLicenseEntry[]>;

const root = process.cwd();
const outputPath = resolve(root, "THIRD-PARTY-NOTICES.md");

const result = spawnSync("pnpm", ["licenses", "list", "--json", "--silent"], {
  cwd: root, env: { ...process.env, NODE_OPTIONS: "--no-deprecation" },
  encoding: "utf8",
  shell: true
});

if (result.status !== 0) {
  console.error("pnpm licenses list failed:", result.stderr);
  process.exit(result.status ?? 1);
}

let report: PnpmLicenseReport;
try {
  report = JSON.parse(result.stdout) as PnpmLicenseReport;
} catch (error) {
  console.error("Failed to parse pnpm licenses JSON:", error);
  process.exit(1);
}

const entries: Array<{ license: string; entry: PnpmLicenseEntry }> = [];
const directNames = directDependencyNames();
for (const [license, items] of Object.entries(report)) {
  for (const item of items) {
    if (directNames.has(item.name)) entries.push({ license, entry: item });
  }
}
entries.sort((a, b) => {
  const nameCmp = a.entry.name.localeCompare(b.entry.name);
  return nameCmp !== 0 ? nameCmp : a.license.localeCompare(b.license);
});

const lockfilePath = resolve(root, "pnpm-lock.yaml");
const lockfileVersion = (() => {
  const text = readFileSync(lockfilePath, "utf8");
  const match = text.match(/^lockfileVersion:\s*['"]?([0-9.]+)/m);
  return match ? match[1] : "unknown";
})();

const generatedAt = new Date().toISOString();
const lines: string[] = [];
lines.push("# Third-party notices");
lines.push("");
lines.push(`Auto-generated by \`pnpm run licenses:generate\` on ${generatedAt}.`);
lines.push("");
lines.push("This file lists direct runtime and development dependencies declared by each workspace,");
lines.push("together with the license declared by each package. It is regenerated whenever");
lines.push("the lockfile changes. Do not edit by hand; CI runs `pnpm run licenses:check` to");
lines.push("fail the build if this file drifts.");
lines.push("");
lines.push(`- pnpm lockfile version: \`${lockfileVersion}\``);
lines.push(`- Total entries: ${entries.length}`);
lines.push("");
lines.push("## License summary");
lines.push("");
const licenseCounts = new Map<string, number>();
for (const { license } of entries) licenseCounts.set(license, (licenseCounts.get(license) ?? 0) + 1);
const sortedLicenses = Array.from(licenseCounts.entries()).sort((a, b) => a[0].localeCompare(b[0]));
for (const [license, count] of sortedLicenses) lines.push(`- \`${license}\`: ${count}`);
lines.push("");
lines.push("## Packages");
lines.push("");
for (const { license, entry } of entries) {
  lines.push(`### ${entry.name}@${entry.versions.join(", ")}`);
  lines.push("");
  lines.push(`- License: \`${license}\``);
  if (entry.author) lines.push(`- Author: ${entry.author}`);
  if (entry.homepage) lines.push(`- Homepage: ${entry.homepage}`);
  if (entry.description) lines.push(`- Description: ${entry.description}`);
  lines.push("");
}

writeFileSync(outputPath, lines.join("\n"), "utf8");
console.log(`Wrote ${entries.length} entries to ${outputPath}`);

function directDependencyNames(): Set<string> {
  const names = new Set<string>();
  for (const relativePath of ["package.json", "apps/admin/package.json"]) {
    const packageJson = JSON.parse(readFileSync(resolve(root, relativePath), "utf8")) as {
      dependencies?: Record<string, string>;
      devDependencies?: Record<string, string>;
      optionalDependencies?: Record<string, string>;
    };
    for (const field of ["dependencies", "devDependencies", "optionalDependencies"] as const) {
      for (const name of Object.keys(packageJson[field] ?? {})) names.add(name);
    }
  }
  return names;
}
